point_cloud_topic: "/camera/depth/color/points"
map_frame_id: "odom"
sensor_frame_id: "/camera_link"
robot_base_frame_id: "base_link"
robot_pose_with_covariance_topic: "/odom_to_pose/pose_cov"
robot_pose_cache_size: 200
track_point_frame_id: "base_link"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
